### ISSUE TITLE
DEPRECATION WARNING: alias_method_chain is deprecated

### ISSUE THREAD

**Issue by marcusg** [akalyaev/valle#26]
Get this warning with Rails 5
```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.
```

The method is called here: https://github.com/akalyaev/valle/blob/8db3a7fc27df0b7187b56976884cf7bc784deeb1/lib/valle/hooks.rb#L27

**Comment by akalyaev** [comment]
How can I reproduce it? What Ruby version are you using?

**Comment by akalyaev** [comment]
Fixed
