### ISSUE TITLE
Automatic table names are broken in Rails 5

### ISSUE THREAD

**Issue by oliverklee** [akalyaev/valle#31]
When using the ApplicationRecord class that was introduced in Rails 5, the automatic table names are broken.

About the ApplicationRecord class:
http://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html

A new Rails application without valle and with a simple Book model (that has just a "title" attribute) works like this:
```
klee@gonzales:~/src/ruby/rails-new$ bin/rails c
Running via Spring preloader in process 16671
Loading development environment (Rails 5.0.0.1)
2.3.1 :001 > Book.table_name
 => "books" 
```

After adding valle to the Gemfile, the output looks like this:
```
klee@gonzales:~/src/ruby/rails-new$ bin/rails c
Running via Spring preloader in process 16814
Loading development environment (Rails 5.0.0.1)
2.3.1 :001 > Book.table_name
 => "application_records" 
```

My educated guess is that valle needs to add its methods to the ApplicationRecord class instead of the ActiveRecord::Base class for Rails 5.

**Comment by akalyaev** [comment]
@oliverklee thank you for such detailed issue 👍  your guess proved to be right, so it was very easy to fix.

`1.1.3` should be working fine in Rails 5
